### ISSUE TITLE
disable github pages until information is minimally accurate

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BioC2019#2]
- [x] disable github pages
- [x] remove sponsors
- [x] update location & dates

**Comment by mtmorgan** [comment]
github pages disabled

**Comment by omsai** [comment]
The [travel-accomodations.md](/Bioconductor/BioC2019/blob/master/docs/travel-accommodations.md) page is the last thing that needs updating to close this out.  To avoid bothering the local organizer, Tom, I thought I could scrape off that information from the Rockefeller website, but they only seem to direct people to their campus map.  I've contacted Rockefeller's public relations about travel information for international visitors because that's information they should be making available anyway.

**Comment by lwaldron** [comment]
It's time to re-enable github pages.
